name: build-rabbitmq-4-1

on: workflow_dispatch

jobs:
  rabbitmq-4-1:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: release/next
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: images/rabbitmq/4.1
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            markoshust/magento-rabbitmq:4.1
            markoshust/magento-rabbitmq:4.1-0
