name: Magento CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Docker Compose
        run: |
          docker compose -f compose.yaml up -d --build

      - name: Run Magento Setup
        run: |
          docker compose exec app bin/magento setup:upgrade
          docker compose exec app bin/magento setup:static-content:deploy -f

      - name: Run Magento Tests (optional)
        run: |
          docker compose exec app vendor/bin/phpunit